### ISSUE TITLE
Firefox keyup event not firing

### ISSUE THREAD

**Issue by craftdelivery** [aaditmshah/capsLock#6]
This is not working on firefox (mac). I've looked into it a bit and it seems that the keyup event does not fire for the capslock key.

This [demo](https://mattiassundling.github.io/react-is-caps-lock-active/) has the same issue

**Comment by aaditmshah** [comment]
Thanks for bringing this to my attention. I found the following bug report for Firefox which documents the behavior you mentioned.

https://bugzilla.mozilla.org/show_bug.cgi?id=712535

Unfortunately, the Firefox developers deemed this to be a `WONTFIX` issue. I tried to think of alternative ways to make it work but to no avail.

Fortunately, `capsLock` corrects itself when the user starts typing. Hence, it's not a lost cause. Here's the demo.

https://raw.githack.com/aaditmshah/capsLock/master/demo.html

I'm closing this issue for now but if I find a way to solve this problem, I'll let you know.

**Comment by craftdelivery** [comment]
Thanks, although it does not correct itself in firefox as far as I can tell.

**Comment by aaditmshah** [comment]
I just tested it on Firefox version 54 on my Mac and it does indeed correct itself once you start typing. If it doesn't work for you, could you possibly create an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) for me to debug? Also, do specify the version of the operating system and Firefox that you're using.

**Comment by KateRoseMorley** [comment]
This problem can be worked around by registering the same listener against both `keydown` and `keyup` and checking the result of `getModifierState('CapsLock')`, as shown at https://iamkate.com/code/caps-lock/
